// src/layouts/DefaultLayout.vue
<template>
    <div class="bg-base-200 text-base-content flex h-full flex-col font-sans">
        <DefaultHeader />

        <main class="flex-auto">
            <RouterView />
        </main>

        <DefaultFooter />
    </div>
</template>

<script setup lang="ts">
import DefaultHeader from '@/components/layouts/DefaultHeader.vue';
import DefaultFooter from '@/components/layouts/DefaultFooter.vue';
</script>

// src/app/layouts/default-layout/default-layout.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { HeaderComponent } from '@/layouts/default-layout/header/header.component';
import { FooterComponent } from '@/layouts/default-layout/footer/footer.component';
@Component({
    selector: 'app-default-layout',
    imports: [RouterOutlet, HeaderComponent, FooterComponent],
    templateUrl: './default-layout.component.html',
})
export class DefaultLayoutComponent {}

<div class="bg-base-200 text-base-content flex h-full flex-col font-sans">
    <app-header />

    <main role="main" class="flex-auto">
        <router-outlet />
    </main>

    <app-footer />
</div>
